version: '3'
services:

    ganache:
        #image: trufflesuite/ganache-cli:v6.7.0
        #volumes:
        #    - "${PWD}/docker/data:/ganache:rw"

        image: trufflesuite/ganache-cli:v6.9.0

        user: "1000:1000"
        network_mode: host
        command:
            - "--accounts"
            - "20"
            - "--defaultBalanceEther"
            - "10000"
            - "--mnemonic"
            #- "${XBR_HDWALLET_SEED}"
            - "myth like bonus scare over problem client lizard pioneer submit female collect"

            # https://ethereum.stackexchange.com/questions/62466/how-to-set-maximum-block-gas-in-ganache-cli
            #- "--gasLimit"
            #- "0xfffffffffff"
            #- "0x1fffffffffffff"
            #- "--gasPrice"
            #- "1"

            - "--gasLimit"
            - "10000000"
            #- "--gasPrice"
            #- "9000000000"

            - "--port"
            - "1545"
            - "--networkId"
            - "5777"
            #- "--db"
            #- "/ganache"

    # docker attach
    truffle:
        depends_on:
          - ganache
        image: crossbario/truffle
        build:
          context: docker
        command: bash
        stdin_open: true
        tty: true
        network_mode: host
        volumes:
          - ./:/code:rw

    crossbar:
        depends_on:
          - ganache
        image: crossbario/crossbarfx:latest
        # UID:GID => id -u, id -g
        user: "1000:1000"
        network_mode: host
        #ports:
        #    - "8080:8080"
        volumes:
            - "${PWD}/teststack/crossbar:/node"
